app/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func
class Notes(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(128))
    username = db.Column(db.String(150),unique=True)
    password = db.Column(db.String(150))
    notes = db.relationship('Notes')

app/__init__.py
from flask import Flask, url_for
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "secret_key_for_cookie_session_and_etc.:D"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app) # initial database 
    from .views import views
    from .auth import auth

    app.register_blueprint(views,url_perfix='/')
    app.register_blueprint(auth,url_perfix='/')
    
    from .models import Users, Notes

    with app.app_context():
        db.create_all()
    login_manager = LoginManager()
    login_manager.login_view = 'auth.sign_in'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return Users.query.get(int(id))

    return app

app/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from .models import Users
from . import db
from werkzeug.security import generate_password_hash , check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
auth = Blueprint("auth",__name__)

@auth.route("/sign-in",methods=['GET','POST'])
def sign_in():
    if request.method == "POST":
        data = request.form
        username = data.get("username")
        password = data.get("password")

        if len(username) < 3:
            flash("username must be greather than 3 charechters.",category='error')
        elif len(password) < 7:
            flash("password must be greather than 7 charechters.",category='error') 
        else:
            user = Users.query.filter_by(username=username).first()
            if user:
                if check_password_hash(user.password,password):
                    flash("Login was successful.", category='success')
                    login_user(user=user,remember=True)
                    return redirect(url_for("views.home"))
                else:
                    flash("Password or Username is incorrect.", category='error')


    return render_template('signin.html',user=current_user  )

@auth.route("/sign-up", methods=['GET','POST'])
def sign_up():
    if request.method  == "POST":
        data = request.form
        fullName = data.get('fullName')
        username = data.get('username')
        fpassword = data.get('password')
        passwordConfirm = data.get('passwordConfirm')
        user = Users.query.filter_by(username=username).first()
        if user:
            flash("username is already exists try aother one.", category="error")
        elif len(fullName) < 2:
            flash("FullName must be greather than 1 charachter.", category="error")
        elif len(username) < 3:
            flash("username must be greather than 2 charachters.", category="error")
        elif fpassword != passwordConfirm:
            flash("passwords is not equal.", category="error")
        elif len(fpassword) < 7:
            flash("password length must be greather than 6 charachter.", category="error")
        else:
            new_user = Users(full_name=fullName,username=username,password=generate_password_hash(fpassword,method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash("Account Created!",category="success")
            return redirect(url_for('views.home'))
             

    return render_template('signup.html',user=current_user)

@auth.route("/sign-out")
@login_required
def sign_out():
    logout_user()
    return redirect(url_for("auth.sign_in"))

app/views.py
from flask import Blueprint, render_template , request, flash, jsonify
from flask_login import login_required, current_user
from . import db
import json
from .models import Notes
views = Blueprint("views",__name__)

@views.route("/",methods=["GET","POST"])
@login_required
def home():
    if request.method == 'POST':
        data = request.form.get('note')
        if len(data) < 1:
            flash("Note is to short!", category='error')
        else:
            new_notes = Notes(data=data, user_id=current_user.id)
            flash("Note added", category='success')
            db.session.add(new_notes)
            db.session.commit()
        
    return render_template("home.html",user=current_user)
@views.route('/delete-note',methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note["noteId"]
    note = Notes.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- bootstrap cdn  -->
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  /> <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    {% block head%} {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Flask App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item ">
              <a class="nav-link" href={{url_for('views.home')}}>Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={{url_for('auth.sign_out')}}>Sign out</a>
            </li>
            {% else %}
            <li class="nav-item ">
              <a class="nav-link" href={{url_for('auth.sign_in')}}>Sign In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={{url_for('auth.sign_up')}}>Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages%}
        {% if category == "error" %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%else%}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%endif%}
        {% endfor %}
      {% endwith %}
    {%block body%}{%endblock%}
    <div class="container">
        {% block container%}
        {% endblock %}
    </div>
    <div class="footer">
        {% block footer%}
        {% endblock %}
    </div>
    <!-- bootstrap cdn  -->
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script src={{url_for('static',filename='javascript/index.js')}}></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

app/templates/home.html
{% extends "base.html" %}
{% block title %}
    Note Taking.
{% endblock %}
{% block container %}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush">
    {% for note in user.notes %}
    <li class="list-group-item">
        {{ note.data }}
    </li>
    <button type="button" class="close" onclick="deleteNote({{ note.id }})">
        <span aria-hidden="true">&times;</span>
    </button>
    {% endfor %}
</ul>
<form method="POST">
    <div class="form-group mt-4">
        <label for="Note">New Note:</label>
        <textarea id="Note" class="form-control" name="note" aria-label="Note" placeholder="Write a new Note..."></textarea>
        <button class="btn btn-primary mt-2"  type="submit">
            Add
        </button>
    </div>
  </form>
{% endblock %}

app/templates/signin.html
{% extends "base.html" %}

{% block title %} Sign In Page {% endblock %}

{% block container %}
<div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mt-5">Sign In</h2>
      <form method="POST">
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="rememberMe">
          <label class="form-check-label" for="rememberMe">Remember me</label>
        </div>
        <button type="submit" class="btn btn-primary w-100">Sign In</button>
      </form>
      <div class="text-center mt-3">
        <a href="#">Forgot password?</a>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% block title %}
Sign Up Page
{% endblock %}
{% block container%}
<div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center mt-5">Sign Up</h2>
      <form method="POST">
        <div class="mb-3">
          <label for="name" class="form-label">Full Name</label>
          <input type="text" class="form-control" id="name" name="fullName" required>
        </div>
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <div class="mb-3">
            <label for="re-password" class="form-label">Repeat Password</label>
            <input type="password" class="form-control" id="re-password" name="passwordConfirm" required>
          </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="terms">
          <label class="form-check-label" for="terms">I agree to the terms and conditions.</label>
        </div>
        <button type="submit" class="btn btn-primary w-100">Sign Up</button>
      </form>
    </div>
  </div>
  {% endblock %}